name: Esegui test Python con pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codice
        uses: actions/checkout@v5

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip

      - name: Esegui test con pytest
        run: |
          python -m unittest test.py
